util.AddNetworkString("MyCarDealer_SaveConfig")
util.AddNetworkString("MyCarDealer_RemoveVehicleFromDB")
util.AddNetworkString("MyCarDealer_RequestLogs")
util.AddNetworkString("MyCarDealer_SendLogs")

net.Receive("MyCarDealer_SaveConfig", function(len, ply)
    if not MyCarDealer.IsAdmin(ply) then
        MyCarDealer.ChatPrint(ply, "Keine Berechtigung!")
        return
    end
    
    local vehicles = net.ReadTable()
    
    -- Validate
    if not istable(vehicles) then return end
    
    -- Generate config file content
    local configContent = [[
-- ============================================
-- Dynora CarDealer - Vehicle Config
-- Auto-generated by Admin Menu
-- ============================================

MyCarDealer.Vehicles = {
]]

    for _, v in ipairs(vehicles) do
        configContent = configContent .. [[
    {
        id = "]] .. v.id .. [[",
        name = "]] .. v.name .. [[",
        category = "]] .. v.category .. [[",
        price = ]] .. v.price .. [[,
        model = "]] .. v.model .. [[",
        class = "]] .. v.class .. [[",
]]
        if v.job then
            configContent = configContent .. [[        job = "]] .. v.job .. [[",
]]
        else
            configContent = configContent .. [[        job = nil,
]]
        end
        
        configContent = configContent .. [[        maxSpeed = ]] .. (v.maxSpeed or 250) .. [[,
        description = "]] .. (v.description or "") .. [[",
        previewColor = Color(]] .. (v.previewColor and v.previewColor.r or 255) .. ", " .. 
                     (v.previewColor and v.previewColor.g or 255) .. ", " .. 
                     (v.previewColor and v.previewColor.b or 255) .. [[)
    },
]]
    end
    
    configContent = configContent .. "}\n"
    
    -- Save to file
    if not file.Exists("cardealer", "DATA") then
        file.CreateDir("cardealer")
    end
    
    file.Write("cardealer/config_vehicles.txt", configContent)
    
    MyCarDealer.ChatPrint(ply, "Config gespeichert! " .. #vehicles .. " Fahrzeuge in config_vehicles.txt")
    MyCarDealer.Log("CONFIG_SAVE", ply, "Saved " .. #vehicles .. " vehicles to config")
    
    -- Broadcast update to all clients
    net.Start("MyCarDealer_ConfigUpdated")
    net.WriteTable(vehicles)
    net.Broadcast()
end)

-- NEU: Fahrzeug komplett entfernen (Config + DB)
net.Receive("MyCarDealer_RemoveVehicleFromDB", function(len, ply)
    if not MyCarDealer.IsAdmin(ply) then
        MyCarDealer.ChatPrint(ply, "Keine Berechtigung!")
        return
    end
    
    local vehicleID = net.ReadString()
    
    -- 1. Aus ALLEN Inventaren entfernen
    local deleteQuery = string.format(
        "DELETE FROM mycardealer_inventory WHERE vehicle_id = %s",
        sql.SQLStr(vehicleID)
    )
    sql.Query(deleteQuery)
    
    -- 2. LVS Items entfernen
    sql.Query(string.format(
        "DELETE FROM mycardealer_lvs_items WHERE vehicle_id = %s",
        sql.SQLStr(vehicleID)
    ))
    
    -- 3. Aktive Fahrzeuge entfernen und Spieler benachrichtigen
    local affectedPlayers = {}
    for _, p in ipairs(player.GetAll()) do
        if IsValid(p.MyCarDealer_Vehicle) and p.MyCarDealer_Vehicle.CD_VehicleID == vehicleID then
            p.MyCarDealer_Vehicle:Remove()
            p.MyCarDealer_Vehicle = nil
            MyCarDealer.SetActiveVehicle(p, "")
            MyCarDealer.ChatPrint(p, "[Dynora Motor´s] Dein Fahrzeug wurde vom Admin entfernt.")
            table.insert(affectedPlayers, p:Nick())
        end
        -- Sync fuer alle
        MyCarDealer.SyncInventory(p)
    end
    
    -- 4. Auch aus der aktuellen Config loeschen und speichern
    local found = false
    for i, v in ipairs(MyCarDealer.Vehicles) do
        if v.id == vehicleID then
            table.remove(MyCarDealer.Vehicles, i)
            found = true
            break
        end
    end
    
    if found then
        -- Neu speichern
        local configContent = "-- Dynora CarDealer - Vehicle Config\n-- Auto-generated after removal\n\nMyCarDealer.Vehicles = {\n"
        for _, v in ipairs(MyCarDealer.Vehicles) do
            configContent = configContent .. "    {id=\"" .. v.id .. "\",name=\"" .. v.name .. "\",category=\"" .. v.category .. "\",price=" .. v.price .. ",model=\"" .. v.model .. "\",class=\"" .. v.class .. "\","
            if v.job then configContent = configContent .. "job=\"" .. v.job .. "\"," end
            configContent = configContent .. "maxSpeed=" .. (v.maxSpeed or 250) .. ",description=\"" .. (v.description or "") .. "\"},\n"
        end
        configContent = configContent .. "}"
        file.Write("cardealer/config_vehicles.txt", configContent)
    end
    
    MyCarDealer.Log("ADMIN_REMOVE_VEHICLE", ply, "Removed " .. vehicleID .. " from all players" .. (#affectedPlayers > 0 and " (affected: " .. table.concat(affectedPlayers, ", ") .. ")" or ""))
    MyCarDealer.ChatPrint(ply, "Fahrzeug '" .. vehicleID .. "' aus DB und allen Inventaren entfernt.")
    if #affectedPlayers > 0 then
        MyCarDealer.ChatPrint(ply, "Betroffene Spieler: " .. table.concat(affectedPlayers, ", "))
    end
end)

-- NEU: Logs an Admin senden
net.Receive("MyCarDealer_RequestLogs", function(len, ply)
    if not MyCarDealer.IsAdmin(ply) then return end
    
    net.Start("MyCarDealer_SendLogs")
    net.WriteTable(MyCarDealer.Logs or {})
    net.Send(ply)
end)

-- Load saved config on startup
hook.Add("Initialize", "MyCarDealer_LoadSavedConfig", function()
    timer.Simple(3, function()
        local saved = file.Read("cardealer/config_vehicles.txt", "DATA")
        if saved then
            print("[Dynora Motor´s] Found saved vehicle config in data/cardealer/config_vehicles.txt")
            print("[Dynora Motor´s] To apply: Copy contents to addons/cardealer/lua/cardealer/config.lua")
        end
    end)
end)

print("[Dynora Motor´s] sv_admin.lua loaded (Config Editor + Vehicle Removal + Logs)")